test_that("sample matching is by ID rather than row order", {
  f <- fixture(); on.exit(unlink(f$root,recursive=TRUE))
  original <- validate_study(f$path)
  path <- file.path(f$root,"bacteria.tsv")
  x <- read.delim(path,check.names=FALSE)
  write_input(x[nrow(x):1,],path)
  expect_equal(validate_study(f$path)$bacteria$clr,original$bacteria$clr)
  x$sample_id[1] <- "unknown"
  write_input(x,path)
  expect_error(validate_study(f$path),"exactly match")
})

test_that("invalid counts, missing metadata, and duplicate visits are rejected", {
  f <- fixture(); on.exit(unlink(f$root,recursive=TRUE))
  path <- file.path(f$root,"bacteria.tsv"); x <- read.delim(path)
  bad <- x; bad[1,2] <- -1; write_input(bad,path)
  expect_error(validate_study(f$path),"nonnegative")
  bad <- x; bad[1,2] <- 0.5; write_input(bad,path)
  expect_error(validate_study(f$path),"integers")
  bad <- x; bad[1,-1] <- 0; write_input(bad,path)
  expect_error(validate_study(f$path),"zero-total")
  write_input(x,path)
  path <- file.path(f$root,"metadata.tsv"); md <- read.delim(path)
  bad <- md; bad$age_baseline[1] <- NA; write_input(bad,path)
  expect_error(validate_study(f$path),"Missing values")
  bad <- md; bad$time[2] <- bad$time[1]; write_input(bad,path)
  expect_error(validate_study(f$path),"Duplicate participant/time")
})

test_that("group changes and rank-deficient adjustments fail explicitly", {
  f <- fixture(); on.exit(unlink(f$root,recursive=TRUE))
  path <- file.path(f$root,"metadata.tsv"); md <- read.delim(path)
  bad <- md; bad$group[1] <- "semaglutide"; write_input(bad,path)
  expect_error(validate_study(f$path),"constant within participant")
  md$age_duplicate <- md$age_baseline; write_input(md,path)
  edit_config(f,covariates=c("age_baseline","age_duplicate"))
  expect_error(validate_study(f$path),"rank deficient")
})

test_that("CLR uses all nonzero features before prevalence filtering", {
  f <- fixture(); on.exit(unlink(f$root,recursive=TRUE))
  low <- validate_study(f$path)
  edit_config(f,min_prevalence=0.9)
  high <- validate_study(f$path)
  expect_lt(length(high$bacteria$keep),length(low$bacteria$keep))
  expect_equal(high$bacteria$clr,low$bacteria$clr)
  expect_equal(unname(rowMeans(high$bacteria$clr)),rep(0,nrow(high$metadata)),tolerance=1e-12)
})

test_that("relative proportions, optional phages, and a single cohort work", {
  f <- fixture(); on.exit(unlink(f$root,recursive=TRUE))
  path <- file.path(f$root,"bacteria.tsv"); x <- read.delim(path)
  x[,-1] <- x[,-1]/rowSums(x[,-1]); write_input(x,path)
  edit_config(f,abundance_scale="relative",phages=NULL,host_links=NULL,group_reference=NULL)
  study <- validate_study(f$path)
  expect_null(study$phages)
  expect_equal(levels(study$metadata$group),"single_cohort")
  x[,-1] <- x[,-1]*100; write_input(x,path)
  expect_error(validate_study(f$path),"not percentages")
})

test_that("configuration typos and unknown host identifiers are rejected", {
  f <- fixture(); on.exit(unlink(f$root,recursive=TRUE))
  edit_config(f,min_prevalance=0.2)
  expect_error(validate_study(f$path),"Unknown configuration")
  cfg <- yaml::read_yaml(f$path); cfg$min_prevalance <- NULL; yaml::write_yaml(cfg,f$path)
  path <- file.path(f$root,"host_links.tsv"); x <- read.delim(path)
  x$host_id[1] <- "missing"; write_input(x,path)
  expect_error(validate_study(f$path),"missing or all-zero")
})
